# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_1 || ORIG_REF_NAME==design_1_microblaze_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mutex_0_1/design_1_mutex_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mutex_0_1 || ORIG_REF_NAME==design_1_mutex_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mailbox_0_1/design_1_mailbox_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mailbox_0_1 || ORIG_REF_NAME==design_1_mailbox_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_4/design_1_dlmb_v10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_4 || ORIG_REF_NAME==design_1_dlmb_v10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_4/design_1_ilmb_v10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_4 || ORIG_REF_NAME==design_1_ilmb_v10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_4/design_1_dlmb_bram_if_cntlr_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_4 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_4/design_1_ilmb_bram_if_cntlr_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_4 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_4/design_1_lmb_bram_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_4 || ORIG_REF_NAME==design_1_lmb_bram_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_3/design_1_microblaze_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_3 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_3/design_1_microblaze_0_axi_intc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_3 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_3/design_1_microblaze_0_xlconcat_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_3 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_4/design_1_mdm_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_4 || ORIG_REF_NAME==design_1_mdm_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_100M_3/design_1_rst_ps8_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_3 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/TAlars/Documents/vivado_projects_tests/vipix/multi_proc/multi_proc/multi_proc.gen/sources_1/bd/design_1/design_1_ooc.xdc
