-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    adr : IN STD_LOGIC_VECTOR (7 downto 0);
    we : IN STD_LOGIC;
    cyc : IN STD_LOGIC;
    stb : IN STD_LOGIC;
    wb_in : IN STD_LOGIC_VECTOR (7 downto 0);
    rx : IN STD_LOGIC;
    tx : OUT STD_LOGIC;
    ack : OUT STD_LOGIC;
    uart_out : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.294000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=119,HLS_SYN_LUT=376,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_36_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_36_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_36_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv8_FC : STD_LOGIC_VECTOR (7 downto 0) := "11111100";

    signal state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal tx_ff : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal j : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    signal baud_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    signal uart_rd_shift_V : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal uart_wr_shift_V : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal ap_phi_mux_tx_ff_flag_0_phi_fu_152_p22 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal state_load_load_fu_405_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1019_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln54_1_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rx_read_read_fu_90_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_488_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_i_new_0_phi_fu_221_p22 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln79_fu_504_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_j_flag_0_phi_fu_258_p22 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_j_new_0_phi_fu_296_p22 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln111_fu_551_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln46_fu_437_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_phi_ln186_phi_fu_333_p22 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln798_1_fu_459_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln798_fu_533_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_next_state_1_phi_fu_361_p22 : STD_LOGIC_VECTOR (1 downto 0);
    signal next_state_fu_600_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_400_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_2_fu_449_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_1_fu_523_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_2_fu_613_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln779_fu_480_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln779_fu_484_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_1_fu_523_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln54_fu_576_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln54_fu_576_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln54_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln54_1_fu_582_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln61_fu_588_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln61_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln61_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1669_fu_609_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    baud_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                baud_count <= ap_const_lv32_36_3;
            elsif (((grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                baud_count <= ap_const_lv32_36_2;
            elsif (((grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                baud_count <= ap_const_lv32_36_1;
            elsif ((((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                baud_count <= grp_fu_400_p2;
            end if; 
        end if;
    end process;

    uart_rd_shift_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                if (((grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3))) then 
                    uart_rd_shift_V <= p_Result_1_fu_523_p4;
                elsif (((rx_read_read_fu_90_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_2))) then 
                    uart_rd_shift_V <= p_Result_2_fu_449_p4;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_tx_ff_flag_0_phi_fu_152_p22 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                i <= ap_phi_mux_i_new_0_phi_fu_221_p22;
                tx_ff <= ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_phi_mux_j_flag_0_phi_fu_258_p22 = ap_const_lv1_1))) then
                j <= ap_phi_mux_j_new_0_phi_fu_296_p22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                state <= ap_phi_mux_next_state_1_phi_fu_361_p22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2))) then
                    uart_wr_shift_V(7 downto 1) <= p_Val2_2_fu_613_p4(7 downto 1);    uart_wr_shift_V(9) <= p_Val2_2_fu_613_p4(9);
            end if;
        end if;
    end process;
    uart_wr_shift_V(0) <= '0';
    uart_wr_shift_V(8) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    ack_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_405_p1, rx_read_read_fu_90_p2, grp_fu_395_p2, icmp_ln80_fu_511_p2, icmp_ln112_fu_558_p2)
    begin
        if ((((icmp_ln112_fu_558_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ack <= ap_const_logic_1;
        elsif ((((icmp_ln112_fu_558_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ack <= ap_const_logic_0;
        else 
            ack <= 'X';
        end if; 
    end process;

    add_ln111_fu_551_p2 <= std_logic_vector(unsigned(j) + unsigned(ap_const_lv32_1));
    add_ln79_fu_504_p2 <= std_logic_vector(unsigned(i) + unsigned(ap_const_lv32_1));
    and_ln54_1_fu_582_p1 <= (0=>we, others=>'-');
    and_ln54_1_fu_582_p2 <= (and_ln54_fu_576_p2 and and_ln54_1_fu_582_p1);
    and_ln54_fu_576_p0 <= (0=>stb, others=>'-');
    and_ln54_fu_576_p1 <= (0=>cyc, others=>'-');
    and_ln54_fu_576_p2 <= (and_ln54_fu_576_p1 and and_ln54_fu_576_p0);
    and_ln61_fu_594_p2 <= (xor_ln61_fu_588_p2 and and_ln54_fu_576_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_phi_mux_i_new_0_phi_fu_221_p22_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_405_p1, icmp_ln1019_fu_570_p2, and_ln54_1_fu_582_p2, grp_fu_395_p2, icmp_ln80_fu_511_p2, add_ln79_fu_504_p2)
    begin
        if (((icmp_ln80_fu_511_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_i_new_0_phi_fu_221_p22 <= add_ln79_fu_504_p2;
        elsif ((((icmp_ln80_fu_511_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = and_ln54_1_fu_582_p2) and (icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_i_new_0_phi_fu_221_p22 <= ap_const_lv32_0;
        elsif (((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2))) then 
            ap_phi_mux_i_new_0_phi_fu_221_p22 <= ap_const_lv32_1;
        else 
            ap_phi_mux_i_new_0_phi_fu_221_p22 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_j_flag_0_phi_fu_258_p22_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_405_p1, icmp_ln1019_fu_570_p2, and_ln54_1_fu_582_p2, rx_read_read_fu_90_p2, grp_fu_395_p2, icmp_ln80_fu_511_p2, icmp_ln112_fu_558_p2)
    begin
        if ((((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_j_flag_0_phi_fu_258_p22 <= ap_const_lv1_0;
        elsif ((((icmp_ln112_fu_558_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln112_fu_558_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = and_ln54_1_fu_582_p2) and (icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2)))) then 
            ap_phi_mux_j_flag_0_phi_fu_258_p22 <= ap_const_lv1_1;
        else 
            ap_phi_mux_j_flag_0_phi_fu_258_p22 <= "X";
        end if; 
    end process;


    ap_phi_mux_j_new_0_phi_fu_296_p22_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_405_p1, icmp_ln1019_fu_570_p2, and_ln54_1_fu_582_p2, grp_fu_395_p2, icmp_ln112_fu_558_p2, add_ln111_fu_551_p2)
    begin
        if (((icmp_ln112_fu_558_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_j_new_0_phi_fu_296_p22 <= add_ln111_fu_551_p2;
        elsif ((((icmp_ln112_fu_558_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = and_ln54_1_fu_582_p2) and (icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2)))) then 
            ap_phi_mux_j_new_0_phi_fu_296_p22 <= ap_const_lv32_1;
        else 
            ap_phi_mux_j_new_0_phi_fu_296_p22 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_next_state_1_phi_fu_361_p22_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_405_p1, icmp_ln1019_fu_570_p2, and_ln54_1_fu_582_p2, rx_read_read_fu_90_p2, grp_fu_395_p2, icmp_ln80_fu_511_p2, icmp_ln112_fu_558_p2, next_state_fu_600_p3)
    begin
        if ((((icmp_ln112_fu_558_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_next_state_1_phi_fu_361_p22 <= ap_const_lv2_3;
        elsif ((((icmp_ln112_fu_558_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_next_state_1_phi_fu_361_p22 <= ap_const_lv2_0;
        elsif (((ap_const_lv1_0 = and_ln54_1_fu_582_p2) and (icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_next_state_1_phi_fu_361_p22 <= next_state_fu_600_p3;
        elsif ((((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2)))) then 
            ap_phi_mux_next_state_1_phi_fu_361_p22 <= ap_const_lv2_1;
        else 
            ap_phi_mux_next_state_1_phi_fu_361_p22 <= "XX";
        end if; 
    end process;


    ap_phi_mux_phi_ln186_phi_fu_333_p22_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_405_p1, icmp_ln1019_fu_570_p2, and_ln54_1_fu_582_p2, rx_read_read_fu_90_p2, grp_fu_395_p2, icmp_ln80_fu_511_p2, icmp_ln112_fu_558_p2, trunc_ln46_fu_437_p1, trunc_ln798_1_fu_459_p1, trunc_ln798_fu_533_p1)
    begin
        if ((((icmp_ln112_fu_558_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln112_fu_558_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_phi_ln186_phi_fu_333_p22 <= trunc_ln798_fu_533_p1;
        elsif (((rx_read_read_fu_90_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_phi_ln186_phi_fu_333_p22 <= trunc_ln798_1_fu_459_p1;
        elsif ((((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = and_ln54_1_fu_582_p2) and (icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2)))) then 
            ap_phi_mux_phi_ln186_phi_fu_333_p22 <= trunc_ln46_fu_437_p1;
        else 
            ap_phi_mux_phi_ln186_phi_fu_333_p22 <= "XXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_tx_ff_flag_0_phi_fu_152_p22_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_405_p1, icmp_ln1019_fu_570_p2, and_ln54_1_fu_582_p2, rx_read_read_fu_90_p2, grp_fu_395_p2, icmp_ln80_fu_511_p2, icmp_ln112_fu_558_p2)
    begin
        if ((((icmp_ln112_fu_558_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln112_fu_558_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_tx_ff_flag_0_phi_fu_152_p22 <= ap_const_lv1_0;
        elsif ((((icmp_ln80_fu_511_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = and_ln54_1_fu_582_p2) and (icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2)))) then 
            ap_phi_mux_tx_ff_flag_0_phi_fu_152_p22 <= ap_const_lv1_1;
        else 
            ap_phi_mux_tx_ff_flag_0_phi_fu_152_p22 <= "X";
        end if; 
    end process;


    ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22_assign_proc : process(tx_ff, ap_CS_fsm_state1, state_load_load_fu_405_p1, icmp_ln1019_fu_570_p2, and_ln54_1_fu_582_p2, rx_read_read_fu_90_p2, grp_fu_395_p2, icmp_ln80_fu_511_p2, icmp_ln112_fu_558_p2, p_Result_s_fu_488_p3)
    begin
        if ((((icmp_ln80_fu_511_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln80_fu_511_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22 <= p_Result_s_fu_488_p3;
        elsif ((((icmp_ln112_fu_558_p2 = ap_const_lv1_0) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln112_fu_558_p2 = ap_const_lv1_1) and (grp_fu_395_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_fu_395_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((rx_read_read_fu_90_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22 <= tx_ff;
        elsif ((((icmp_ln1019_fu_570_p2 = ap_const_lv1_0) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = and_ln54_1_fu_582_p2) and (icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22 <= ap_const_lv1_1;
        elsif (((icmp_ln1019_fu_570_p2 = ap_const_lv1_1) and (state_load_load_fu_405_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln54_1_fu_582_p2))) then 
            ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22 <= ap_const_lv1_0;
        else 
            ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22 <= "X";
        end if; 
    end process;

    grp_fu_395_p2 <= "1" when (baud_count = ap_const_lv32_1) else "0";
    grp_fu_400_p2 <= std_logic_vector(unsigned(baud_count) + unsigned(ap_const_lv32_FFFFFFFF));
    icmp_ln1019_fu_570_p2 <= "1" when (adr = ap_const_lv8_FC) else "0";
    icmp_ln112_fu_558_p2 <= "1" when (signed(add_ln111_fu_551_p2) > signed(ap_const_lv32_9)) else "0";
    icmp_ln80_fu_511_p2 <= "1" when (signed(add_ln79_fu_504_p2) > signed(ap_const_lv32_A)) else "0";
    next_state_fu_600_p3 <= 
        ap_const_lv2_2 when (and_ln61_fu_594_p2(0) = '1') else 
        ap_const_lv2_0;
    p_Result_1_fu_523_p3 <= (0=>rx, others=>'-');
    
    p_Result_1_fu_523_p4_proc : process(uart_rd_shift_V, j, p_Result_1_fu_523_p3)
    begin
        p_Result_1_fu_523_p4 <= uart_rd_shift_V;
        if to_integer(unsigned(j)) >= uart_rd_shift_V'low and to_integer(unsigned(j)) <= uart_rd_shift_V'high then
            p_Result_1_fu_523_p4(to_integer(unsigned(j))) <= p_Result_1_fu_523_p3(0);
        end if;
    end process;

    
    p_Result_2_fu_449_p4_proc : process(uart_rd_shift_V)
    begin
        p_Result_2_fu_449_p4 <= uart_rd_shift_V;
        p_Result_2_fu_449_p4(0) <= ap_const_lv1_0(0);
    end process;

    p_Result_s_fu_488_p3 <= sext_ln779_fu_480_p1(to_integer(unsigned(trunc_ln779_fu_484_p1)) downto to_integer(unsigned(trunc_ln779_fu_484_p1))) when (to_integer(unsigned(trunc_ln779_fu_484_p1)) >= 0 and to_integer(unsigned(trunc_ln779_fu_484_p1)) <=10) else "-";
    p_Val2_2_fu_613_p4 <= ((ap_const_lv2_2 & trunc_ln1669_fu_609_p1) & ap_const_lv1_0);
    rx_read_read_fu_90_p2 <= (0=>rx, others=>'-');
        sext_ln779_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(uart_wr_shift_V),11));

    state_load_load_fu_405_p1 <= state;
    trunc_ln1669_fu_609_p1 <= wb_in(7 - 1 downto 0);
    trunc_ln46_fu_437_p1 <= uart_rd_shift_V(10 - 1 downto 0);
    trunc_ln779_fu_484_p1 <= i(11 - 1 downto 0);
    trunc_ln798_1_fu_459_p1 <= p_Result_2_fu_449_p4(10 - 1 downto 0);
    trunc_ln798_fu_533_p1 <= p_Result_1_fu_523_p4(10 - 1 downto 0);
    tx <= ap_phi_mux_tx_ff_loc_0_phi_fu_190_p22(0);
    uart_out <= ap_phi_mux_phi_ln186_phi_fu_333_p22;
    xor_ln61_fu_588_p0 <= (0=>we, others=>'-');
    xor_ln61_fu_588_p2 <= (xor_ln61_fu_588_p0 xor ap_const_lv1_1);
end behav;
